sonar.projectKey=mlops-stock
sonar.projectName=MLOps-Stock
sonar.python.version=3.11

# Thu muc chua source code
sonar.sources=src,services

# Thu muc chua test
sonar.tests=tests

# Duong dan file bao cao coverage duoc tao tu pytest
sonar.python.coverage.reportPaths=coverage.xml

# Loai bo cac thu muc khong can quet
sonar.exclusions=venv/**,tests/**,**/*.md,**/*.txt
